export const pdfTranslations = {
  english: {
    noTransactions: "No transactions available to generate report.",
    errorGeneratingPDF: "Error generating PDF:",
    companyName: "MASCOT RMS",
    reportTitle: "Monthly Financial Report",
    month: "Month",
    generated: "Generated",
    incomeLedgers: "INCOME LEDGERS",
    expenseLedgers: "EXPENSE LEDGERS", 
    overallSummary: "OVERALL SUMMARY",
    ledgerName: "Ledger Name",
    recovery: "Recovery",
    expense: "Expense",
    totalRecovery: "Total Recovery",
    totalExpense: "Total Expense",
    netBalance: "Net Balance",
    page: "Page",
    of: "of",
    generatedBy: "Generated by Mascot RMS System",
    currency: "Rs.",
    months: [
      "January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"
    ]
  },
  
  urdu: {
    noTransactions: "کوئی لین دین دستیاب نہیں ہے۔ رپورٹ بنانے کے لیے",
    errorGeneratingPDF: "پی ڈی ایف بنانے میں خرابی:",
    companyName: "ماسکوٹ آر ایم ایس",
    reportTitle: "ماہانہ مالی رپورٹ",
    month: "ماہ",
    generated: "تیاری کی تاریخ",
    incomeLedgers: "آمدنی کے لیجرز",
    expenseLedgers: "اخراجات کے لیجرز",
    overallSummary: "مجموعی خلاصہ",
    ledgerName: "لیجر کا نام",
    recovery: "وصولی",
    expense: "خرچہ",
    totalRecovery: "کل وصولی",
    totalExpense: "کل خرچ",
    netBalance: "خالص بیلنس",
    page: "صفحہ",
    of: "از",
    generatedBy: "ماسکوٹ آر ایم ایس سسٹم کے ذریعے تیار کردہ",
    currency: "روپے",
    months: [
      "جنوری", "فروری", "مارچ", "اپریل", "مئی", "جون",
      "جولائی", "اگست", "ستمبر", "اکتوبر", "نومبر", "دسمبر"
    ]
  }
};